presets:
  main:
    name: main
    description: main
    windowMode: current-window
    layout:
      type: horizontal
      ratio: [1, 1]
      panes:
        - type: vertical
          ratio: [1, 1]
          panes:
            - name: postman
              command: nix run github:i9wa4/tmux-a2a-postman --refresh
              delay: 500
              focus: true
            - name: agent
              command: export A2A_NODE=watchdog claude-chill -- claude --dangerously-skip-permissions --model sonnet
              delay: 500
        - name: gtop
          command: gtop
          delay: 500

  dev:
    name: dev
    description: dev
    windowMode: current-window
    layout:
      type: horizontal
      ratio: [1, 1]
      panes:
        - name: editor
          command: vim
          delay: 500
          focus: true
        - name: agent
          command: claude --dangerously-skip-permissions --model sonnet
          delay: 500

  messenger:
    name: messenger
    description: messenger
    windowMode: current-window
    layout:
      type: horizontal
      ratio: [1, 1]
      panes:
        - name: editor
          command: vim
          delay: 500
          focus: true
        - name: agent
          command: export A2A_NODE=messenger claude --dangerously-skip-permissions --model haiku
          delay: 500

  high:
    name: workers
    description: workers
    windowMode: new-window
    layout:
      type: horizontal
      ratio: [1, 1]
      panes:
        - name: agent
          # command: export A2A_NODE=boss codex --yolo --model gpt-5.3-codex
          command: export A2A_NODE=boss claude --dangerously-skip-permissions --model opus
          delay: 500
        - type: vertical
          ratio: [1, 1, 1, 1]
          panes:
            - name: agent
              command: export A2A_NODE=orchestrator claude --dangerously-skip-permissions --model sonnet
              delay: 500
            - name: agent
              command: export A2A_NODE=worker claude --dangerously-skip-permissions --model sonnet
              delay: 500
            - name: agent
              command: export A2A_NODE=critic claude --dangerously-skip-permissions --model sonnet
              delay: 500
            - name: agent
              command: export A2A_NODE=guardian codex --yolo --model gpt-5.3-codex
              delay: 500
