presets:
  main:
    name: main
    description: main
    windowMode: current-window
    layout:
      type: horizontal
      ratio: [1, 1]
      panes:
        - name: editor
          command: vim
          delay: 500
          focus: true
        - name: postman
          command: ~/ghq/github.com/i9wa4/tmux-a2a-postman/tmux-a2a-postman
          delay: 500

  dev:
    name: dev
    description: dev
    windowMode: current-window
    layout:
      type: horizontal
      ratio: [1, 1]
      panes:
        - name: editor
          command: vim
          delay: 500
          focus: true
        - name: worker
          command: claude-chill -- claude --dangerously-skip-permissions --model sonnet
          delay: 500

  concierge:
    name: orchestrator
    description: orchestrator
    windowMode: current-window
    layout:
      type: horizontal
      ratio: [1, 1]
      panes:
        - name: editor
          command: vim
          delay: 500
          focus: true
        - name: concierge
          command: A2A_NODE=concierge claude-chill -- claude --dangerously-skip-permissions --model sonnet
          delay: 500

  orchestrator:
    name: workers
    description: workers
    windowMode: new-window
    layout:
      type: horizontal
      ratio: [1, 1]
      panes:
        - type: vertical
          ratio: [1, 1]
          panes:
            - name: orchestrator
              # command: A2A_NODE=orchestrator claude-chill -- claude --dangerously-skip-permissions --model opus
              command: A2A_NODE=orchestrator claude-chill -- claude --dangerously-skip-permissions --model sonnet
              delay: 500
            - name: worker
              command: A2A_NODE=worker claude-chill -- claude --dangerously-skip-permissions --model sonnet
              delay: 500
        - type: vertical
          ratio: [1, 1]
          panes:
            - name: observer
              command: A2A_NODE=observer-a-leader claude-chill -- claude --dangerously-skip-permissions --model sonnet
              delay: 500
            - name: observer
              command: A2A_NODE=observer-b-leader codex --yolo
              delay: 500
