presets:
  dev:
    name: dev
    description: dev
    windowMode: current-window
    layout:
      type: horizontal
      ratio: [1, 1]
      panes:
        - name: editor
          command: vim -c "execute 'edit' '.i9wa4/temp.md'->expand()"
          focus: true
        - name: worker
          command: claude --dangerously-skip-permissions
          env:
            A2A_PEER: worker

  orchestrator:
    name: orchestrator
    description: orchestrator
    windowMode: current-window
    layout:
      type: vertical
      ratio: [8, 1]
      panes:
        - type: horizontal
          ratio: [1, 1]
          panes:
            - name: editor
              command: vim -c "execute 'edit' '.i9wa4/temp.md'->expand()"
              focus: true
            - name: orchestrator
              command: claude --dangerously-skip-permissions
              env:
                A2A_PEER: orchestrator
        - type: horizontal
          ratio: [1, 1]
          panes:
            - name: zsh
            - name: postman
              command: uv run ~/ghq/github.com/i9wa4/dotfiles/bin/postman.py
              delay: 10000

  workers:
    name: workers
    description: workers
    windowMode: new-window
    layout:
      type: horizontal
      ratio: [1, 1]
      panes:
        - name: worker
          command: claude --dangerously-skip-permissions
          env:
            A2A_PEER: worker
        - type: vertical
          ratio: [1, 1, 1, 1]
          panes:
            - name: observer
              command: codex --yolo
              env:
                A2A_PEER: observer-codex-1
            - name: observer
              command: codex --yolo
              env:
                A2A_PEER: observer-codex-2
            - name: observer
              command: claude --dangerously-skip-permissions
              env:
                A2A_PEER: observer-claude-1
            - name: observer
              command: claude --dangerously-skip-permissions
              env:
                A2A_PEER: observer-claude-2
