presets:
  dev:
    name: dev
    description: dev
    windowMode: current-window
    layout:
      type: horizontal
      ratio: [1, 1]
      panes:
        - name: editor
          command: vim -c "execute 'edit' '.i9wa4/temp.md'->expand()"
          focus: true
        - name: claude
          command: claude --dangerously-skip-permissions

  orchestrator:
    name: orchestrator
    description: orchestrator
    windowMode: current-window
    layout:
      type: vertical
      ratio: [8, 1]
      panes:
        - type: horizontal
          ratio: [1, 1]
          panes:
            - name: editor
              command: vim -c "execute 'edit' '.i9wa4/temp.md'->expand()"
              focus: true
            - name: orchestrator
              command: AGENT_ROLE=orchestrator claude --dangerously-skip-permissions
        - name: postman
          command: uv run ~/ghq/github.com/i9wa4/dotfiles/bin/postman.py

  workers:
    name: workers
    description: workers
    windowMode: new-window
    layout:
      type: vertical
      ratio: [1, 1]
      panes:
        - type: horizontal
          ratio: [1, 1]
          panes:
            - name: codex
              command: AGENT_ROLE=worker-r-codex codex --yolo
            - name: claude
              command: AGENT_ROLE=worker-w-claude claude --dangerously-skip-permissions
        - type: horizontal
          ratio: [1, 1, 1, 1]
          panes:
            - name: observer
              command: AGENT_ROLE=observer-codex-1 codex --yolo
            - name: observer
              command: AGENT_ROLE=observer-codex-2 codex --yolo
            - name: observer
              command: AGENT_ROLE=observer-claude-1 claude --dangerously-skip-permissions
            - name: observer
              command: AGENT_ROLE=observer-claude-2 claude --dangerously-skip-permissions
