[tools]
# Package managers
uv = "0.9.18"

# Development tools
pre-commit = "4.5.1"
shellcheck = "0.11.0"
shfmt = "3.12.0"

# Aqua tools
"aqua:gitleaks/gitleaks" = "8.30.0"
"aqua:rhysd/actionlint" = "1.7.9"
"aqua:suzuki-shunsuke/ghalint" = "1.5.4"
"aqua:suzuki-shunsuke/ghatm" = "1.0.0"
"aqua:suzuki-shunsuke/pinact" = "3.6.0"
"aqua:zizmorcore/zizmor" = "1.18.0"
