[tools]
# Tools for CI
"aqua:JohnnyMorganz/StyLua"    = "2.3.1"
"aqua:gitleaks/gitleaks"       = "8.30.0"
"aqua:rhysd/actionlint"        = "1.7.9"
"aqua:suzuki-shunsuke/ghalint" = "1.5.4"
"aqua:suzuki-shunsuke/ghatm"   = "1.0.0"
"aqua:suzuki-shunsuke/pinact"  = "3.7.3"
"aqua:zizmorcore/zizmor"       = "1.19.0"
pre-commit                     = "4.5.1"
shellcheck                     = "0.11.0"
shfmt                          = "3.12.0"
uv                             = "0.9.18"

# Tools not in nixpkgs
"github:jameswoolfenden/pike"  = "0.3.87"
"github:rhysd/vim-startuptime" = "1.3.2"
"github:rvben/rumdl"           = "0.0.206"
