[settings]
experimental = true

[tools]
# Language Runtimes
deno  = "2.6.0"
go    = "latest"
node  = "24"
rust  = "latest"
uv    = "latest"

# CLI Tools
act             = "latest"
awscli          = "latest"
databricks-cli  = "latest"
fd              = "latest"
fzf             = "latest"
gcloud          = "latest"
gh              = "latest"
hadolint        = "latest"
jq              = "latest"
pre-commit      = "latest"
ripgrep         = "latest"
shellcheck      = "latest"
shfmt           = "latest"
terraform       = "latest"
tflint          = "latest"

# Cargo Tools
"cargo:bat" = "latest"
"cargo:rumdl" = "latest"
"cargo:tokei" = "latest"

# Aqua Tools
# "aqua:evilmartians/lefthook"  = "latest"
# "aqua:mikefarah/yq"           = "latest"
"aqua:rhysd/actionlint"          = "latest"
"aqua:suzuki-shunsuke/pinact"    = "latest"
"aqua:x-motemen/ghq"             = "latest"
"aqua:zizmorcore/zizmor"         = "latest"
"aqua:gitleaks/gitleaks"         = "latest"

# Go Tools
# "go:github.com/jameswoolfenden/pike"  = { version = "latest" }
"go:github.com/mattn/efm-langserver"  = { version = "latest" }
"go:github.com/rhysd/vim-startuptime" = { version = "latest" }
