[[plugins]]
repo = 'rhysd/vim-healthcheck'
on_cmd = ['CheckHealth']

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_event = ['VimEnter']

[[plugins]]
repo = 'mattn/vim-lsp-settings'
on_source = ['vim-lsp']
hook_add = '''
let g:lsp_diagnostics_float_cursor = v:true
let g:lsp_diagnostics_virtual_text_align = "after"
let g:lsp_diagnostics_virtual_text_wrap = "truncate"
'''
hook_source = '''
let g:lsp_log_file = ''
let g:lsp_settings_enable_suggestions = v:false
let g:lsp_settings = {
\   'efm-langserver': {
\     'disabled': v:false,
\   },
\   'nixd': {
\     'disabled': v:false,
\     },
\   },
\ }

augroup MyLspSetting
  autocmd!
  autocmd BufWritePre * if !v:cmdbang | execute 'LspDocumentFormatSync' | endif
augroup END
'''

[[plugins]]
repo = 'Shougo/ddc-source-lsp'
on_source = ['ddc.vim']
