[general]
import = [
    '~/.config/alacritty/theme.toml',
    '~/.config/alacritty/opacity.toml'
]

[font]
size = 24

[font.normal]
family = "UDEV Gothic 35LG"

[window]
startup_mode = "Maximized"

[keyboard]
bindings = []
