# lazygit configuration
# cf. https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
customCommands:
  - key: "<c-g>"
    description: "Switch repository (ghq)"
    prompts:
      - type: "menuFromCommand"
        title: "Select repository"
        command: "ghq list"
        filter: "(?P<repo>.*)"
        valueFormat: "{{ .repo }}"
        labelFormat: "{{ .repo }}"
    command: 'lazygit --path "$(ghq root)/{{index .PromptResponses 0}}"'
    context: "global"
    subprocess: true
