hide_agent_reasoning = true
model = "gpt-5.1-codex-max"
model_reasoning_effort = "high"
network_access = true
notify = ["printf", "\\a"]

[features]
web_search_request = true

[mcp_servers.aws_documentation]
command = "uvx"
args = ["awslabs.aws-documentation-mcp-server@latest"]
enabled = false
