hide_agent_reasoning = true
# model = "gpt-5.2-codex"
model_reasoning_effort = "high"
network_access = true
notify = ["sh", "-c", "printf '\\a'"]

[analytics]
enabled = false

[feedback]
enabled = false

[features]
skills = true
web_search_request = true

# [mcp_servers.aws_documentation]
# command = "uvx"
# args = ["awslabs.aws-documentation-mcp-server@latest"]
# enabled = false
