# https://developers.openai.com/codex/config-basic
# https://developers.openai.com/codex/config-advanced

hide_agent_reasoning = true
network_access = true
# notify = ["sh", "-c", "printf '\\a'"]
project_doc_fallback_filenames = ["README.md", "CONTRIBUTING.md"]
web_search = "live"

[analytics]
enabled = false

[feedback]
enabled = false

[features]
collab = true
skills = true

# [mcp_servers.aws_documentation]
# command = "uvx"
# args = ["awslabs.aws-documentation-mcp-server@latest"]
# enabled = false
